// בס"ד
import { partition } from "@repo/array-functions";
import { useMemo, type FC } from "react";
import { FaRegClock } from "react-icons/fa";
import { LuUsers } from "react-icons/lu";
import { LuHash } from "react-icons/lu";

 const FRC_TEAMS = [
  {
    address: null,
    city: "Modi'in-Maccabim Reu't",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1937",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Lior Shemer Furniture/Keren Lahaim Foundation/Municipality of Modi'in-Maccabim-Reut/Israeli Ministry Of Education/Apple&Maccabim Reut Mor High School&Ironi Alef Modiin High School",
    nickname: "Elysium",
    postal_code: "7179902",
    rookie_year: 2006,
    school_name:
      "Ironi Alef Modiin High School & Maccabim Reut Mor High School",
    stateProvidence: "HaMerkaz",
    teamNumber: 1937,
    website: "https://www.frcelysium1937.wixsite.com/1937",
  },
  {
    address: null,
    city: "Petah-Tikva",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4320",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "AMAL 1/Peled Tech/Tel-Aviv University&AMAL B",
    nickname: "The Joker",
    postal_code: "99999",
    rookie_year: 2012,
    school_name: "AMAL B",
    stateProvidence: "HaMerkaz",
    teamNumber: 4320,
    website: "https://frcthejoker4320.wixsite.com/team4320",
  },
  {
    address: null,
    city: "Drom HaSharon Regional Council ",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11070",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Yarkon High School",
    nickname: "RoboRex",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Yarkon High School",
    stateProvidence: "HaMerkaz",
    teamNumber: 11070,
    website: null,
  },
  {
    address: null,
    city: "hispin",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11329",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "00000",
    nickname: "G-Force",
    postal_code: null,
    rookie_year: 2026,
    school_name: "00000",
    stateProvidence: "HaZafon",
    teamNumber: 11329,
    website: null,
  },
  {
    address: null,
    city: "ramat gan",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11332",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Begin High School Ramat Gan",
    nickname: "Sunrise",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Begin High School Ramat Gan",
    stateProvidence: "Tel-Aviv",
    teamNumber: 11332,
    website: null,
  },
  {
    address: null,
    city: "Magen",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11390",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Nofei Habsor",
    nickname: "Habsor",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Nofei Habsor",
    stateProvidence: "HaDarom",
    teamNumber: 11390,
    website: null,
  },
  {
    address: null,
    city: "Oranit",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11471",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Family/Community",
    nickname: "Neon",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Family/Community",
    stateProvidence: "HaMerkaz",
    teamNumber: 11471,
    website: null,
  },
  {
    address: null,
    city: "kfar kasem",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11478",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "kfar kasim school",
    nickname: "Nexus",
    postal_code: null,
    rookie_year: 2026,
    school_name: "kfar kasim school",
    stateProvidence: "HaMerkaz",
    teamNumber: 11478,
    website: null,
  },
  {
    address: null,
    city: "LOD",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11480",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Tzvia Elyashiv Lod צביה אלישיב לוד",
    nickname: "EXODUS",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Tzvia Elyashiv Lod צביה אלישיב לוד",
    stateProvidence: "HaMerkaz",
    teamNumber: 11480,
    website: null,
  },
  {
    address: null,
    city: "Misgav",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1574",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Iscar/AKAD Progressive Dies/Gelfand Family Charitable Trust/Ministry of Education/JCA Charitable Foundation/Ledico Bosch/Klil Industries/Elbit Systems Cyclone/Volta Belting/Studio Keren/Noga Tools/Mirtec/Micro Metal Industries/Digmey Hagalil/Canopia by Palram/Jabil Shemer/KeyShot&Misgav High School",
    nickname: "MisCar",
    postal_code: "2017900",
    rookie_year: 2005,
    school_name: "Misgav High School",
    stateProvidence: "HaZafon",
    teamNumber: 1574,
    website: "http://miscar1574.org",
  },
  {
    address: null,
    city: "Raanana",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1577",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Apple - Israel/Bosh - Israel/PEI Genesis  /Bar-Yadin Family/REV Robotics&Aviv High School - Raanana",
    nickname: "Steampunk",
    postal_code: "43399",
    rookie_year: 2005,
    school_name: "Aviv High School - Raanana",
    stateProvidence: "HaMerkaz",
    teamNumber: 1577,
    website: "http://www.steampunk1577.org",
  },
  {
    address: null,
    city: "Ashkelon",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1580",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Ort Henri ronson",
    nickname: "The Blue Monkeys",
    postal_code: "78150",
    rookie_year: 2005,
    school_name: "Ort Henri ronson",
    stateProvidence: "HaDarom",
    teamNumber: 1580,
    website: "http://henri-ronson.ort.org.il/first/index.htm",
  },
  {
    address: null,
    city: "Binyamina",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1690",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Binyamina - Givat Ada Local Council/Ministry of Education/zivudim/ARAN/SCOPUSTECH/Dassault Systèmes&cramim atid binyamina",
    nickname: "Orbit",
    postal_code: "3050654",
    rookie_year: 2005,
    school_name: "cramim atid binyamina",
    stateProvidence: "HaZafon",
    teamNumber: 1690,
    website: "http://www.1690orbit.com",
  },
  {
    address: null,
    city: "Gadera",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1942",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "IAF-ASSOCIATION/ROBOTEC TECNOLOGIES(INTELITEK)/IAF-DEPOT 22 & 0RT ISRAEL & ORT TEL NOF",
    nickname: "Cinderella Tel-Nof",
    postal_code: "77400",
    rookie_year: 2006,
    school_name: "0RT ISRAEL & ORT TEL NOF",
    stateProvidence: "HaMerkaz",
    teamNumber: 1942,
    website: "http:///telnof.ort.org.il",
  },
  {
    address: null,
    city: "Lod",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2212",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Motorola Solutions IL/ELAL&Atid Lod",
    nickname: "The Spikes",
    postal_code: "71106",
    rookie_year: 2007,
    school_name: "Atid Lod",
    stateProvidence: "HaMerkaz",
    teamNumber: 2212,
    website: "http://spikes2212.com/",
  },
  {
    address: null,
    city: "Herzliya",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2230",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "General Motors/Herzliya Municipality&Handasaim Herzliya",
    nickname: "General Angels",
    postal_code: "4680002",
    rookie_year: 2007,
    school_name: "Handasaim Herzliya",
    stateProvidence: "HaMerkaz",
    teamNumber: 2230,
    website: "https://www.ga2230.com",
  },
  {
    address: null,
    city: "Shoham",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2231",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Extal/Shoham’s City Council/Ledico BOSCH/Fabric/Qualcomm/Sherman Manufacturing Solutions/Gene Hass Foundation/Monday.com/Gravograph&SHOHAM",
    nickname: "OnyxTronix",
    postal_code: "60850",
    rookie_year: 2007,
    school_name: "SHOHAM",
    stateProvidence: "HaMerkaz",
    teamNumber: 2231,
    website: "https://onyxtronix2231.wixsite.com/home",
  },
  {
    address: null,
    city: "Jerusalem",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2679",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Mobileye/FIRST Hardship Grant/Petrus/BRM/MTM/BTI2XL/Hi-Tech Mechanics/Hi-Tech Engineering Pvt&The Hebrew University Secondary School",
    nickname: "Atlantis",
    postal_code: "95435",
    rookie_year: 2008,
    school_name: "The Hebrew University Secondary School",
    stateProvidence: "Yerushalayim",
    teamNumber: 2679,
    website: "https://www.facebook.com/TigerTeam2679/",
  },
  {
    address: null,
    city: "Jatt",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3065",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: 'GI GAZI  INDUSTRIES - METAL - גאזי תעשיות מתכת בע"מ ---ELECTRICAL Engineering  - Jamal  Gazi&jatt Highschool',
    nickname: "Jatt High School",
    postal_code: "71799",
    rookie_year: 2009,
    school_name: "jatt Highschool",
    stateProvidence: "HaMerkaz",
    teamNumber: 3065,
    website: "http://www.jatt-highschool.net",
  },
  {
    address: null,
    city: "Hod Hasharon",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3075",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Hod HaSharon Municipality/Zivud & Metal Packaging/Mobileye/Chevron /Su-Pad/Keysight/Alony-Hetz/Ayecka/SIG - Signature Investment Group/A. Bachar Milling & Turning,/Conlog&Hadarim High School",
    nickname: "Ha-Dream Team",
    postal_code: "45101",
    rookie_year: 2009,
    school_name: "Hadarim High School",
    stateProvidence: "HaMerkaz",
    teamNumber: 3075,
    website: "http://hadream3075.com/",
  },
  {
    address: null,
    city: "Maagan Michael",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3083",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Plasson/Suron/Rotary/Adobe/HOF CARMEL HIGH SCHOOL/CHEVRON/ZINGER LTD&HOME SCHOOL",
    nickname: "Artemis",
    postal_code: "37805",
    rookie_year: 2009,
    school_name: "HOME SCHOOL",
    stateProvidence: "HaZafon",
    teamNumber: 3083,
    website: "http://www.artemis3083.org",
  },
  {
    address: null,
    city: "Tel Aviv",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3316",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Tel-Aviv Municipality/Ministry of Education/Apple/HP Indigo/The Altshuler Shaham Group/NFX Guild/Gal-Esh/Jet-Laser/Shtil Neeman/Shivrug&Ironi Daled",
    nickname: "D-Bug",
    postal_code: "6226205",
    rookie_year: 2010,
    school_name: "Ironi Daled",
    stateProvidence: "Tel-Aviv",
    teamNumber: 3316,
    website: "https://www.team3316.com",
  },
  {
    address: null,
    city: "Kfar Yona",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3339",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Gal-Kifuf/Rabina/Unique Designs/Essence/Ledico/Siemens/Ministry of Education/Ministry of Science & Ish Shalom",
    nickname: "BumbleB",
    postal_code: "4032522",
    rookie_year: 2010,
    school_name: "Ish Shalom",
    stateProvidence: "HaMerkaz",
    teamNumber: 3339,
    website: "https://www.bumbleb3339.com",
  },
  {
    address: null,
    city: "Tel Aviv",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3835",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Tel Aviv Municipality/PTC/Gudes Badim&Tichon Hadash Tel Aviv",
    nickname: "Vulcan",
    postal_code: "62337",
    rookie_year: 2011,
    school_name: "Tichon Hadash Tel Aviv",
    stateProvidence: "Tel-Aviv",
    teamNumber: 3835,
    website: "https://www.team3835.org",
  },
  {
    address: null,
    city: "Ramat Hasharon",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4416",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Ramat HaSharon Municipality - Rothberg, and Alon/Mobileye Vision Technologies Ltd./Ledico Ltd./Robotic Systems - Israel Aerospace Industries Ltd.&Alon&Rothberg",
    nickname: "Skynet",
    postal_code: "00000",
    rookie_year: 2012,
    school_name: "Rothberg & Alon",
    stateProvidence: "HaMerkaz",
    teamNumber: 4416,
    website: "http://www.rocket4416.com",
  },
  {
    address: null,
    city: "Modi'in",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4586",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Apple/Google/Suzuki/ShaGal Marketing Solutions Ltd./Masaeiot/Dfus Natali/Ofer Falafel/Ledico/Bank Hapoalim/Pet-it/Ituran/The Association for the Elderly in Modi'in/Ministry of Education/Modi'in-Maccabim-Re'ut Municipality&Ironi B Modi'in",
    nickname: "PRIMO",
    postal_code: "7179556",
    rookie_year: 2013,
    school_name: "Ironi B Modi'in",
    stateProvidence: "HaMerkaz",
    teamNumber: 4586,
    website: "http://primo4586.co.il/",
  },
  {
    address: null,
    city: "Hakfar Hayarok",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4590",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Hakfar Hayarok School & Hakfar Hayarok",
    nickname: "GreenBlitz",
    postal_code: "4780000",
    rookie_year: 2013,
    school_name: "Hakfar Hayarok",
    stateProvidence: "Tel-Aviv",
    teamNumber: 4590,
    website: "http://www.firstinspires.org/",
  },
  {
    address: null,
    city: "Hadera",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4744",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Amal group/Ministry of Education&AMAL HADERA of science & arts",
    nickname: "Ninjas",
    postal_code: "3852512",
    rookie_year: 2013,
    school_name: "AMAL HADERA of science & arts",
    stateProvidence: "Haifa",
    teamNumber: 4744,
    website: "http://4744ninjas.wixsite.com/ninjas",
  },
  {
    address: null,
    city: "HOLON",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5614",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Perion Network Ltd.&Katzir Gymnasium",
    nickname: "Team Sycamore",
    postal_code: "5845100",
    rookie_year: 2015,
    school_name: "Katzir Gymnasium",
    stateProvidence: "HaMerkaz",
    teamNumber: 5614,
    website: "http://teamsycamore5614.org",
  },
  {
    address: null,
    city: "Dabburiya",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5715",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Dabburiya Local Council&Dabburiya High School",
    nickname: "DRC",
    postal_code: "1691000",
    rookie_year: 2015,
    school_name: "Dabburiya High School",
    stateProvidence: "HaZafon",
    teamNumber: 5715,
    website: "http://www.firstinspires.org/",
  },
  {
    address: null,
    city: "Modiin",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5990",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "&Amit Boys Modiin",
    nickname: "TRIGON",
    postal_code: "7178079",
    rookie_year: 2016,
    school_name: "Amit Boys Modiin",
    stateProvidence: "HaMerkaz",
    teamNumber: 5990,
    website: "http://www.trigonfrc.info",
  },
  {
    address: null,
    city: "Pardes Hana",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6740",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Shvilim Democratic School",
    nickname: "G3 - Glue Gun & Glitter",
    postal_code: "37100",
    rookie_year: 2017,
    school_name: "Shvilim Democratic School",
    stateProvidence: "Haifa",
    teamNumber: 6740,
    website: "https://www.g3-6740.org/",
  },
  {
    address: null,
    city: "PARDES HANA",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc7039",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Neurim",
    nickname: "❌⭕",
    postal_code: "4227822",
    rookie_year: 2018,
    school_name: "Neurim",
    stateProvidence: "HaMerkaz",
    teamNumber: 7039,
    website: null,
  },
  {
    address: null,
    city: "Jerusalem",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc7845",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "PICO Kids/Ministry of Education&Himmelfarb High School",
    nickname: "8BIT",
    postal_code: "9639005",
    rookie_year: 2019,
    school_name: "Himmelfarb High School",
    stateProvidence: "Yerushalayim",
    teamNumber: 7845,
    website: null,
  },
  {
    address: null,
    city: "Emek Yizrael",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc8175",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Jezreel Valley Regional Council&Family/Community",
    nickname: "Piece of Mind",
    postal_code: "3659000",
    rookie_year: 2020,
    school_name: "Family/Community",
    stateProvidence: "HaZafon",
    teamNumber: 8175,
    website: null,
  },
  {
    address: null,
    city: "Tel Aviv",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc8223",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Ironi H",
    nickname: "Mariners",
    postal_code: "6350220",
    rookie_year: 2020,
    school_name: "Ironi H",
    stateProvidence: "Tel-Aviv",
    teamNumber: 8223,
    website: null,
  },
  {
    address: null,
    city: "GIVAT SHMUEL",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9303",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "ישיבת בני עקיבא גבעת שמואל",
    nickname: "PORTAL",
    postal_code: null,
    rookie_year: 2023,
    school_name: "ישיבת בני עקיבא גבעת שמואל",
    stateProvidence: "HaMerkaz",
    teamNumber: 9303,
    website: null,
  },
];

interface TeamSelectProps {
  teamNumber?: number;
  recency?: number;
  setTeamNumber: (team: number | null) => void;
  setRecency: (recency: number | null) => void;
  scoutedTeams: number[];
}

const EMPTY_INPUT = 0;

export const TeamSelect: FC<TeamSelectProps> = ({
  teamNumber,
  recency,
  setTeamNumber,
  setRecency,
  scoutedTeams,
}) => {
  const { true: actualScoutedTeams, false: otherTeams } = useMemo(
    () =>
      partition(FRC_TEAMS, (team) => scoutedTeams.includes(team.teamNumber)),
    [scoutedTeams],
  );
  return (
    <div className="flex flex-col sm:flex-row gap-3 w-full max-w-md mx-auto p-4 bg-slate-900/40 backdrop-blur-sm rounded-2xl border border-white/10 shadow-2xl">
      <div className="relative flex-1">
        <div className="absolute left-3 top-1/2 -translate-y-1/2 text-emerald-500/50">
          <LuHash size={16} />
        </div>
        <input
          onChange={(event) => {
            setTeamNumber(
              event.currentTarget.value
                ? Number(event.currentTarget.value)
                : null,
            );
          }}
          value={teamNumber === EMPTY_INPUT ? undefined : teamNumber}
          type="number"
          placeholder="Team #"
          className="w-full pl-8 py-3 bg-slate-950/50 border border-white/5 rounded-xl text-slate-200 placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/40 focus:border-emerald-500/50 transition-all font-mono"
        />
      </div>

      <div className="relative flex-2">
        <div className="absolute left-3 top-1/2 -translate-y-1/2 text-emerald-500/50 pointer-events-none">
          <LuUsers size={16} />
        </div>
        <select
          className="w-full pl-10 pr-4 py-3 bg-slate-950/50 border border-white/5 rounded-xl text-slate-200 appearance-none focus:outline-none focus:ring-2 focus:ring-emerald-500/40 focus:border-emerald-500/50 transition-all cursor-pointer font-bold text-sm"
          onChange={(event) => {
            setTeamNumber(Number(event.currentTarget.value));
          }}
          value={teamNumber ?? "none"}
        >
          <option
            disabled
            value="none"
            selected
            className="bg-slate-900 text-slate-500"
          >
            Select Team
          </option>
          {actualScoutedTeams.map((team) => (
            <option
              key={team.teamNumber}
              value={team.teamNumber}
              className="bg-slate-500 text-slate-200"
            >
              {team.teamNumber} | {team.nickname}
            </option>
          ))}
          {otherTeams.map((team) => (
            <option
              key={team.teamNumber}
              value={team.teamNumber}
              className="bg-red-900 text-slate-200"
            >
              {team.teamNumber} | {team.nickname}
            </option>
          ))}
        </select>
        <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-500">
          <svg
            width="10"
            height="6"
            viewBox="0 0 10 6"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M1 1L5 5L9 1" />
          </svg>
        </div>
      </div>
      <RecencyInput recency={recency} setRecency={setRecency} />
    </div>
  );
};

interface RecencyInputProps {
  recency: number | undefined;
  setRecency: (recency: number | null) => void;
}

export const RecencyInput: FC<RecencyInputProps> = ({
  recency,
  setRecency,
}) => (
  <div className="relative">
    <div className="absolute left-3 top-1/2 -translate-y-1/2 text-emerald-500/50">
      <FaRegClock size={16} />
    </div>
    <input
      onChange={(event) => {
        setRecency(
          event.currentTarget.value ? Number(event.currentTarget.value) : null,
        );
      }}
      value={recency === EMPTY_INPUT ? undefined : recency}
      type="number"
      className="w-20 pl-10 pr-2 py-3 bg-slate-950/50 border border-white/5 rounded-xl text-slate-200 placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/40 focus:border-emerald-500/50 transition-all font-mono"
    />
  </div>
);
