// בס"ד

export const FRC_TEAMS = [
  {
    city: "Misgav",
    country: "Israel",
    key: "frc1574",
    name: "Iscar/AKAD Progressive Dies/Gelfand Family Charitable Trust/Ministry of Education/JCA Charitable Foundation/Ledico Bosch/Klil Industries/Elbit Systems Cyclone/Volta Belting/Studio Keren/Noga Tools/Mirtec/Micro Metal Industries/Digmey Hagalil/Canopia by Palram/Jabil Shemer/KeyShot&Misgav High School",
    nickname: "MisCar",
    stateProvidence: "HaZafon",
    teamNumber: 1574,
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    key: "frc1576",
    name: "Tel Aviv Municipality/Bank Hapoalim & Ironi Chet Reshit & Eroni Chet- rashit",
    nickname: "Voltrix",
    stateProvidence: "Tel-Aviv",
    teamNumber: 1576,
  },
  {
    city: "Raanana",
    country: "Israel",
    key: "frc1577",
    name: "Apple - Israel/Bosh - Israel/PEI Genesis  /Bar-Yadin Family/REV Robotics&Aviv High School - Raanana",
    nickname: "Steampunk",
    stateProvidence: "HaMerkaz",
    teamNumber: 1577,
  },
  {
    city: "Ashkelon",
    country: "Israel",
    key: "frc1580",
    name: "Ort Henri ronson",
    nickname: "The Blue Monkeys",
    stateProvidence: "HaDarom",
    teamNumber: 1580,
  },
  {
    city: "Binyamina",
    country: "Israel",
    key: "frc1690",
    name: "Binyamina - Givat Ada Local Council/Ministry of Education/zivudim/ARAN/SCOPUSTECH/Dassault Systèmes&cramim atid binyamina",
    nickname: "Orbit",
    stateProvidence: "HaZafon",
    teamNumber: 1690,
  },
  {
    city: "Modi'in-Maccabim Reu't",
    country: "Israel",
    key: "frc1937",
    name: "Lior Shemer Furniture/Keren Lahaim Foundation/Municipality of Modi'in-Maccabim-Reut/Israeli Ministry Of Education/Apple&Maccabim Reut Mor High School&Ironi Alef Modiin High School",
    nickname: "Elysium",
    stateProvidence: "HaMerkaz",
    teamNumber: 1937,
  },
  {
    city: "Gadera",
    country: "Israel",
    key: "frc1942",
    name: "IAF-ASSOCIATION/ROBOTEC TECNOLOGIES(INTELITEK)/IAF-DEPOT 22 & 0RT ISRAEL & ORT TEL NOF",
    nickname: "Cinderella Tel-Nof",
    stateProvidence: "HaMerkaz",
    teamNumber: 1942,
  },
  {
    city: "rosh ha'ayin",
    country: "Israel",
    key: "frc1943",
    name: "Begin high school/municipality of Rosh Ha'ain/EID Electronics Ltd&begin high scool",
    nickname: "Neat Team",
    stateProvidence: "HaMerkaz",
    teamNumber: 1943,
  },
  {
    city: "Be'er Sheva",
    country: "Israel",
    key: "frc1954",
    name: "Rash foundation & AMAL RAMOT BEER SHEVA",
    nickname: "ElectroBunny",
    stateProvidence: "HaDarom",
    teamNumber: 1954,
  },
  {
    city: "Dimona",
    country: "Israel",
    key: "frc2096",
    name: "Home Skinovations/InMode/NICE/Hoodies/Medisim/World Ort Education for Life/Darca/Municipality of Dimona/NASA/Marcantil/Negev Nucler Reserch Center/Israel Ministry of Education/Israel Ministry of Science and Technology/The Ministry for Development of the Periphery, the Negev and the Galilee&Zinman high school",
    nickname: "RoboActive",
    stateProvidence: "HaDarom",
    teamNumber: 2096,
  },
  {
    city: "Lod",
    country: "Israel",
    key: "frc2212",
    name: "Motorola Solutions IL/ELAL&Atid Lod",
    nickname: "The Spikes",
    stateProvidence: "HaMerkaz",
    teamNumber: 2212,
  },
  {
    city: "Herzliya",
    country: "Israel",
    key: "frc2230",
    name: "General Motors/Herzliya Municipality&Handasaim Herzliya",
    nickname: "General Angels",
    stateProvidence: "HaMerkaz",
    teamNumber: 2230,
  },
  {
    city: "Shoham",
    country: "Israel",
    key: "frc2231",
    name: "Extal/Shoham’s City Council/Ledico BOSCH/Fabric/Qualcomm/Sherman Manufacturing Solutions/Gene Hass Foundation/Monday.com/Gravograph&SHOHAM",
    nickname: "OnyxTronix",
    stateProvidence: "HaMerkaz",
    teamNumber: 2231,
  },
  {
    city: "Emek Hefer",
    country: "Israel",
    key: "frc2630",
    name: "Emek Hefer/Yarok/Emek Hefer Regional Council/Ramot Yam Regional HS/Ben Gurion Ruppin Regional HS/Isracard/Bar Ilan University&Emek Hefer / Yarok",
    nickname: "Thunderbolts",
    stateProvidence: "HaMerkaz",
    teamNumber: 2630,
  },
  {
    city: "Jerusalem",
    country: "Israel",
    key: "frc2679",
    name: "Mobileye/FIRST Hardship Grant/Petrus/BRM/MTM/BTI2XL/Hi-Tech Mechanics/Hi-Tech Engineering Pvt&The Hebrew University Secondary School",
    nickname: "Atlantis",
    stateProvidence: "Yerushalayim",
    teamNumber: 2679,
  },
  {
    city: "Jatt",
    country: "Israel",
    key: "frc3065",
    name: 'GI GAZI  INDUSTRIES - METAL - גאזי תעשיות מתכת בע"מ ---ELECTRICAL Engineering  - Jamal  Gazi&jatt Highschool',
    nickname: "Jatt High School",
    stateProvidence: "HaMerkaz",
    teamNumber: 3065,
  },
  {
    city: "Hod Hasharon",
    country: "Israel",
    key: "frc3075",
    name: "Hod HaSharon Municipality/Zivud & Metal Packaging/Mobileye/Chevron /Su-Pad/Keysight/Alony-Hetz/Ayecka/SIG - Signature Investment Group/A. Bachar Milling & Turning,/Conlog&Hadarim High School",
    nickname: "Ha-Dream Team",
    stateProvidence: "HaMerkaz",
    teamNumber: 3075,
  },
  {
    city: "Maagan Michael",
    country: "Israel",
    key: "frc3083",
    name: "Plasson/Suron/Rotary/Adobe/HOF CARMEL HIGH SCHOOL/CHEVRON/ZINGER LTD&HOME SCHOOL",
    nickname: "Artemis",
    stateProvidence: "HaZafon",
    teamNumber: 3083,
  },
  {
    city: "Yeruham",
    country: "Israel",
    key: "frc3211",
    name: "The Greater Miami Jewish Federation/The Jewish Agency for Israel/Ministry of Science and Technology/Ministry for Education/The Yeruham Municipality/The Tzivoni Foundation/Padagis/Taipei Economic and Cultural office in Tel Aviv&The Yeurham science center&Ort Sapir Yeruham&Belevav Shalem&Kama",
    nickname: "The Y Team",
    stateProvidence: "HaDarom",
    teamNumber: 3211,
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    key: "frc3316",
    name: "Tel-Aviv Municipality/Ministry of Education/Apple/HP Indigo/The Altshuler Shaham Group/NFX Guild/Gal-Esh/Jet-Laser/Shtil Neeman/Shivrug&Ironi Daled",
    nickname: "D-Bug",
    stateProvidence: "Tel-Aviv",
    teamNumber: 3316,
  },
  {
    city: "Kfar Yona",
    country: "Israel",
    key: "frc3339",
    name: "Gal-Kifuf/Rabina/Unique Designs/Essence/Ledico/Siemens/Ministry of Education/Ministry of Science & Ish Shalom",
    nickname: "BumbleB",
    stateProvidence: "HaMerkaz",
    teamNumber: 3339,
  },
  {
    city: "Gan Yavne",
    country: "Israel",
    key: "frc3388",
    name: "Flash/Aharon Yosef/Bank Hapoalim&Ort Rabin",
    nickname: "Flash in memory of Margarita Gusak",
    stateProvidence: "HaMerkaz",
    teamNumber: 3388,
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    key: "frc3835",
    name: "Tel Aviv Municipality/PTC/Gudes Badim&Tichon Hadash Tel Aviv",
    nickname: "Vulcan",
    stateProvidence: "Tel-Aviv",
    teamNumber: 3835,
  },
  {
    city: "Beer Sheva",
    country: "Israel",
    key: "frc4319",
    name: "SRT/Metal/Beer Sheva/Ben Gurion University of the negev/Rashi Foundation/Ministry of Education&Ulpanat AMIT Oriya",
    nickname: "Ladies FIRST",
    stateProvidence: "HaDarom",
    teamNumber: 4319,
  },
  {
    city: "Petah-Tikva",
    country: "Israel",
    key: "frc4320",
    name: "AMAL 1/Peled Tech/Tel-Aviv University&AMAL B",
    nickname: "The Joker",
    stateProvidence: "HaMerkaz",
    teamNumber: 4320,
  },
  {
    city: "אבן יהודה",
    country: "Israel",
    key: "frc4338",
    name: "Peled Tech&The Walworth Barbour American International School",
    nickname: "Falcons",
    stateProvidence: "HaMerkaz",
    teamNumber: 4338,
  },
  {
    city: "Ramat Hasharon",
    country: "Israel",
    key: "frc4416",
    name: "Ramat HaSharon Municipality - Rothberg, and Alon/Mobileye Vision Technologies Ltd./Ledico Ltd./Robotic Systems - Israel Aerospace Industries Ltd.&Alon&Rothberg",
    nickname: "Skynet",
    stateProvidence: "HaMerkaz",
    teamNumber: 4416,
  },
  {
    city: "Modi'in",
    country: "Israel",
    key: "frc4586",
    name: "Apple/Google/Suzuki/ShaGal Marketing Solutions Ltd./Masaeiot/Dfus Natali/Ofer Falafel/Ledico/Bank Hapoalim/Pet-it/Ituran/The Association for the Elderly in Modi'in/Ministry of Education/Modi'in-Maccabim-Re'ut Municipality&Ironi B Modi'in",
    nickname: "PRIMO",
    stateProvidence: "HaMerkaz",
    teamNumber: 4586,
  },
  {
    city: "Hakfar Hayarok",
    country: "Israel",
    key: "frc4590",
    name: "Hakfar Hayarok School & Hakfar Hayarok",
    nickname: "GreenBlitz",
    stateProvidence: "Tel-Aviv",
    teamNumber: 4590,
  },
  {
    city: "beit hashmonay",
    country: "Israel",
    key: "frc4661",
    name: "hertzog",
    nickname: "Cypher",
    stateProvidence: "HaMerkaz",
    teamNumber: 4661,
  },
  {
    city: "Hadera",
    country: "Israel",
    key: "frc4744",
    name: "Amal group/Ministry of Education&AMAL HADERA of science & arts",
    nickname: "Ninjas",
    stateProvidence: "Haifa",
    teamNumber: 4744,
  },
  {
    city: "Yehud",
    country: "Israel",
    key: "frc5135",
    name: "Trellidor Ltd./Mekif Yehud High School&Mekif Yehud",
    nickname: "Black Unicorns",
    stateProvidence: "HaMerkaz",
    teamNumber: 5135,
  },
  {
    city: "Eilat",
    country: "Israel",
    key: "frc5291",
    name: "Goldwater",
    nickname: "Emperius",
    stateProvidence: "HaDarom",
    teamNumber: 5291,
  },
  {
    city: "Netanya",
    country: "Israel",
    key: "frc5554",
    name: "ORT Netanya Residential Educational Campus&Ort Yad Leibowitz",
    nickname: "The Poros Robotics",
    stateProvidence: "HaMerkaz",
    teamNumber: 5554,
  },
  {
    city: "HOLON",
    country: "Israel",
    key: "frc5614",
    name: "Perion Network Ltd.&Katzir Gymnasium",
    nickname: "Team Sycamore",
    stateProvidence: "HaMerkaz",
    teamNumber: 5614,
  },
  {
    city: "Ness Ziona",
    country: "Israel",
    key: "frc5635",
    name: "ministry of education/The City of Ness Ziona/Orbotech/ledico/argentols/Solidworks/Stratasys/Galshvav/Dantech&ben gorion&Ben Yehuda&Golda Meir",
    nickname: "Demacia",
    stateProvidence: "HaMerkaz",
    teamNumber: 5635,
  },
  {
    city: "Arad",
    country: "Israel",
    key: "frc5654",
    name: "tapuach pais arad",
    nickname: "Phoenix",
    stateProvidence: "HaDarom",
    teamNumber: 5654,
  },
  {
    city: "Dabburiya",
    country: "Israel",
    key: "frc5715",
    name: "Dabburiya Local Council&Dabburiya High School",
    nickname: "DRC",
    stateProvidence: "HaZafon",
    teamNumber: 5715,
  },
  {
    city: "Petah Tikva",
    country: "Israel",
    key: "frc5928",
    name: "Petach Tikva Robotics & Family/Community",
    nickname: "MetalBoost",
    stateProvidence: "HaMerkaz",
    teamNumber: 5928,
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    key: "frc5951",
    name: "Josh and Judy Weston/Tel-Aviv municipality/Tel Aviv foundation&the Natan Alterman school - Tichonet",
    nickname: "Makers Assemble",
    stateProvidence: "Tel-Aviv",
    teamNumber: 5951,
  },
  {
    city: "Haifa",
    country: "Israel",
    key: "frc5987",
    name: "Elbit Systems/The Hebrew Reali school/Sterokem/Yes Planet/Apple/Israel's Ministry of Education/Haifa Technology Center&The Hebrew Reali School in Haifa",
    nickname: "Galaxia in memory of David Zohar",
    stateProvidence: "Haifa",
    teamNumber: 5987,
  },
  {
    city: "Modiin",
    country: "Israel",
    key: "frc5990",
    name: "&Amit Boys Modiin",
    nickname: "TRIGON",
    stateProvidence: "HaMerkaz",
    teamNumber: 5990,
  },
  {
    city: "Ofakim",
    country: "Israel",
    key: "frc6104",
    name: "Science Center Ofakim&Ha Rav - Thumi",
    nickname: "Desert Eagles in memory of Yehonatan Maimon",
    stateProvidence: "HaDarom",
    teamNumber: 6104,
  },
  {
    city: "iksal",
    country: "Israel",
    key: "frc6168",
    name: "alzahrawi junior high school",
    nickname: "alzahrawi",
    stateProvidence: "HaZafon",
    teamNumber: 6168,
  },
  {
    city: "Jerusalem",
    country: "Israel",
    key: "frc6230",
    name: "ORT Harmatz College Givat Ram&ORT Harmatz College Givat Ram",
    nickname: "Team Koi",
    stateProvidence: "Yerushalayim",
    teamNumber: 6230,
  },
  {
    city: "Modi'in",
    country: "Israel",
    key: "frc6738",
    name: 'Yeshivat Bnei Akiva Lapid "Torat Nahum" Modi\'in',
    nickname: "Excalibur",
    stateProvidence: "HaMerkaz",
    teamNumber: 6738,
  },
  {
    city: "Pardes Hana",
    country: "Israel",
    key: "frc6740",
    name: "Shvilim Democratic School",
    nickname: "G3 - Glue Gun & Glitter",
    stateProvidence: "Haifa",
    teamNumber: 6740,
  },
  {
    city: "PARDES HANA",
    country: "Israel",
    key: "frc7039",
    name: "Neurim",
    nickname: "❌⭕",
    stateProvidence: "HaMerkaz",
    teamNumber: 7039,
  },
  {
    city: "Jerusalem ",
    country: "Israel",
    key: "frc7067",
    name: "PICO Kids & seligsberg",
    nickname: "Team Streak",
    stateProvidence: "Yerushalayim",
    teamNumber: 7067,
  },
  {
    city: "Kadima-Zoran",
    country: "Israel",
    key: "frc7112",
    name: "Oded High School",
    nickname: "EverGreen",
    stateProvidence: "HaMerkaz",
    teamNumber: 7112,
  },
  {
    city: "tayibe",
    country: "Israel",
    key: "frc7177",
    name: "Amal Taybe High School",
    nickname: "Turismo",
    stateProvidence: "HaMerkaz",
    teamNumber: 7177,
  },
  {
    city: "Jerusalem",
    country: "Israel",
    key: "frc7845",
    name: "PICO Kids/Ministry of Education&Himmelfarb High School",
    nickname: "8BIT",
    stateProvidence: "Yerushalayim",
    teamNumber: 7845,
  },
  {
    city: "Emek Yizrael",
    country: "Israel",
    key: "frc8175",
    name: "Jezreel Valley Regional Council&Family/Community",
    nickname: "Piece of Mind",
    stateProvidence: "HaZafon",
    teamNumber: 8175,
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    key: "frc8223",
    name: "Ironi H",
    nickname: "Mariners",
    stateProvidence: "Tel-Aviv",
    teamNumber: 8223,
  },
  {
    city: "GIVAT SHMUEL",
    country: "Israel",
    key: "frc9303",
    name: "ישיבת בני עקיבא גבעת שמואל",
    nickname: "PORTAL",
    stateProvidence: "HaMerkaz",
    teamNumber: 9303,
  },
  {
    city: "Sdot negev",
    country: "Israel",
    key: "frc9304",
    name: "Neria high school",
    nickname: "legend's",
    stateProvidence: "HaDarom",
    teamNumber: 9304,
  },
  {
    city: "Tel Mond",
    country: "Israel",
    key: "frc9738",
    name: "Rabin High School Tel Mond",
    nickname: "Ionic Bond",
    stateProvidence: "Tel-Aviv",
    teamNumber: 9738,
  },
  {
    city: "Modi'in-Maccabim-Re'ut",
    country: "Israel",
    key: "frc9739",
    name: "Mobileye/Bnei Akiva&Orot Modiin",
    nickname: "Firefly",
    stateProvidence: "HaMerkaz",
    teamNumber: 9739,
  },
  {
    city: "yavne",
    country: "Israel",
    key: "frc9740",
    name: "ort ormat",
    nickname: "CANBus in memory of Roney Tal",
    stateProvidence: "HaMerkaz",
    teamNumber: 9740,
  },
  {
    city: "Mate Asher",
    country: "Israel",
    key: "frc10139",
    name: "Tsunami R.A.",
    nickname: "Tsunami",
    stateProvidence: "HaZafon",
    teamNumber: 10139,
  },
  {
    city: "Kfar Blum",
    country: "Israel",
    key: "frc10695",
    name: "Emek Hula",
    nickname: "Galileo",
    stateProvidence: "HaZafon",
    teamNumber: 10695,
  },
  {
    city: "Kiryat Ono",
    country: "Israel",
    key: "frc10935",
    name: "Ben Zvi High School",
    nickname: "Krono",
    stateProvidence: "Tel-Aviv",
    teamNumber: 10935,
  },
  {
    city: "Rahat",
    country: "Israel",
    key: "frc10986",
    name: "Alsna",
    nickname: "Negev Dominion",
    stateProvidence: "HaDarom",
    teamNumber: 10986,
  },
  {
    city: "Drom HaSharon Regional Council ",
    country: "Israel",
    key: "frc11070",
    name: "Yarkon High School",
    nickname: "RoboRex",
    stateProvidence: "HaMerkaz",
    teamNumber: 11070,
  },
  {
    city: "hispin",
    country: "Israel",
    key: "frc11329",
    name: "00000",
    nickname: "G-Force",
    stateProvidence: "HaZafon",
    teamNumber: 11329,
  },
  {
    city: "ramat gan",
    country: "Israel",
    key: "frc11332",
    name: "Begin High School Ramat Gan",
    nickname: "Sunrise",
    stateProvidence: "Tel-Aviv",
    teamNumber: 11332,
  },
  {
    city: "Magen",
    country: "Israel",
    key: "frc11390",
    name: "Nofei Habsor",
    nickname: "Eshkol",
    stateProvidence: "HaDarom",
    teamNumber: 11390,
  },
  {
    city: "Oranit",
    country: "Israel",
    key: "frc11471",
    name: "Family/Community",
    nickname: "Neon",
    stateProvidence: "HaMerkaz",
    teamNumber: 11471,
  },
  {
    city: "kfar kasem",
    country: "Israel",
    key: "frc11478",
    name: "kfar kasim school",
    nickname: "KasimTec",
    stateProvidence: "HaMerkaz",
    teamNumber: 11478,
  },
  {
    city: "LOD",
    country: "Israel",
    key: "frc11480",
    name: "Tzvia Elyashiv Lod צביה אלישיב לוד",
    nickname: "EXODUS",
    stateProvidence: "HaMerkaz",
    teamNumber: 11480,
  },
];

export const FRC_TEAM_NUMBERS = FRC_TEAMS.map((team) => team.teamNumber);
