// בס"ד

export const FRC_TEAMS = [
  {
    address: null,
    city: "NOVA MUTUM",
    country: "Brazil",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc10291",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "SENAI MATO GROSSO/SESI MATO GROSSO/QUALCOMM&SENAI MUTUM",
    nickname: "MUTUM-X",
    postal_code: null,
    rookie_year: 2025,
    school_name: "SENAI MUTUM",
    state_prov: "Mato Grosso",
    teamNumber: 10291,
    website: null,
  },
  {
    address: null,
    city: "Oregon",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc10553",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Icon Robotics/Gene Haas Foundation/Alliant Energy/One Community Bank/Omni Technologies/FIRST Wisconsin/Argosy Foundation/Metalcraft Industries/Milwaukee Tool/Oregon School District&Oregon High",
    nickname: "Orange Overdrive",
    postal_code: null,
    rookie_year: 2025,
    school_name: "Oregon High",
    state_prov: "Wisconsin",
    teamNumber: 10553,
    website: null,
  },
  {
    address: null,
    city: "Reno",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc10903",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "The Gillemot Foundation/NASA Robotics Alliance Project/Blue Heaven Restaurant, Key West/The Argosy Foundation/Gene Haas Foundation/NASA+Robonauts 118/Team SOS/FIRST Nevada/To The Stars, Inc./BTechSoft/Univ of Nevada, Reno Aerospace and Defense Academy/Little Swan Dancers/ClickBond/SolUp/RFE International, Inc./Corestone Engineering&Family/Community",
    nickname: "The Ionizers",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Family/Community",
    state_prov: "Nevada",
    teamNumber: 10903,
    website: null,
  },
  {
    address: null,
    city: "Kiryat Ono",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc10935",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Ben Zvi Highschool & Katzir Highschool",
    nickname: "Krono",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Katzir Highschool & Ben Zvi Highschool",
    state_prov: "Tel-Aviv",
    teamNumber: 10935,
    website: null,
  },
  {
    address: null,
    city: "Philadelphia",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc10979",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "TGR Learning Lab/DoD STEM/Comcast&TGR Foundation",
    nickname: "Tiger Robotics",
    postal_code: null,
    rookie_year: 2026,
    school_name: "TGR Foundation",
    state_prov: "Pennsylvania",
    teamNumber: 10979,
    website: null,
  },
  {
    address: null,
    city: "Paola",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1108",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "The Baehr Foundation/Trane/Michael and Lorretta Verhaeghe/Dr. Beth Petelin/Polaris Electronics/Gene Haas Foundation/REV Robotics/Optimum/G.K. Smith and Sons/Novelis/Intuitive Foundation/Westfield Energy/A Razors Edge Tattoo/Emma Ure/Dr. Greg and Karen Windler/KC STEM Alliance/Holman/FG Cardinal/Precision Husky/University of Kansas Health System - Paola/Jennifer and Matt Meek/Paul and Kathy Haley/Bruce Kelly Memorial Foundation/Dean Scherman Memorial Fund/City of Paola&Paola High School",
    nickname: "Panther Robotics",
    postal_code: "66071",
    rookie_year: 2003,
    school_name: "Paola High School",
    state_prov: "Kansas",
    teamNumber: 1108,
    website: "http://www.pantherrobotics.com",
  },
  {
    address: null,
    city: "San Francisco",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc11463",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Sacred Heart Cathedral Preparatory",
    nickname: "SHC Robotics",
    postal_code: null,
    rookie_year: 2026,
    school_name: "Sacred Heart Cathedral Preparatory",
    state_prov: "California",
    teamNumber: 11463,
    website: null,
  },
  {
    address: null,
    city: "Greenville",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc148",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Innovation First International&Greenville High School",
    nickname: "Robowranglers",
    postal_code: "75402",
    rookie_year: 1992,
    school_name: "Greenville High School",
    state_prov: "Texas",
    teamNumber: 148,
    website: "http://www.robowranglers148.com/",
  },
  {
    address: null,
    city: "Portland",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1540",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Polymaker/TEL/FIRST Washington&Catlin Gabel School",
    nickname: "Flaming Chickens",
    postal_code: "97225",
    rookie_year: 2005,
    school_name: "Catlin Gabel School",
    state_prov: "Oregon",
    teamNumber: 1540,
    website: "http://www.team1540.org/",
  },
  {
    address: null,
    city: "Raanana",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1577",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Apple - Israel/Bosh - Israel/PEI Genesis  /Bar-Yadin Family/REV Robotics&Aviv High School - Raanana",
    nickname: "Steampunk",
    postal_code: "43399",
    rookie_year: 2005,
    school_name: "Aviv High School - Raanana",
    state_prov: "HaMerkaz",
    teamNumber: 1577,
    website: "http://www.steampunk1577.org",
  },
  {
    address: null,
    city: "Queens",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1796",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Boyce Technologies/Sunnyside Community Services/West Coast Products/Bloomberg/Gene Haas Foundation/BAE Systems/RoboTigers Alumni Association&Queens Technical High School",
    nickname: "RoboTigers",
    postal_code: "11101",
    rookie_year: 2006,
    school_name: "Queens Technical High School",
    state_prov: "New York",
    teamNumber: 1796,
    website: "http://www.RoboTigers1796.com",
  },
  {
    address: null,
    city: "Stuart",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc180",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Florida Power & Light/REV Robotics &Martin County District Schools",
    nickname: "S.P.A.M.",
    postal_code: "34997",
    rookie_year: 1998,
    school_name: "Martin County District Schools",
    state_prov: "Florida",
    teamNumber: 180,
    website: "http://www.spamrobotics.com",
  },
  {
    address: null,
    city: "Allentown",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1807",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Johnson & Johnson/Kubik - Maltbie/DoD STEM/Lockheed - Martin/Gene Haas Foundation&Allentown High School",
    nickname: "Redbird Robotics",
    postal_code: "08501",
    rookie_year: 2006,
    school_name: "Allentown High School",
    state_prov: "New Jersey",
    teamNumber: 1807,
    website: "https://www.frc1807.org",
  },
  {
    address: null,
    city: "Cumming",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1833",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Advanced Instrument Technologies/Microsoft/Automation Direct/Jones Utilities Construction, Inc./NASA/Ignite Wireless/Banks Bookkeeping/Lead Coverage/Price Industries/BoldVu by MRI/Intuitive Foundation Grant/ADP/Cobb Community Foundation/Allstate/Conway & Owen/Gene Haas Foundation Grant/Agilox/PTC Grant/Thrifty Bot/Atlanta Creative Graphics Inc/Hopewell Designs, Inc/TAG Inc/Intuitive Foundation Grant/Trent Callan/Formlabs/David and Mary Kelton/Avery Banks/Kelton Holdings/Empower Sports Chiropractic&Family/Community",
    nickname: "Team BEAN",
    postal_code: null,
    rookie_year: 2006,
    school_name: "Family/Community",
    state_prov: "Georgia",
    teamNumber: 1833,
    website: null,
  },
  {
    address: null,
    city: "London",
    country: "United Kingdom",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1884",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Dojo/Gene Haas Foundation&The American School in London",
    nickname: "Griffins",
    postal_code: "NW8 0NP",
    rookie_year: 2006,
    school_name: "The American School in London",
    state_prov: "England",
    teamNumber: 1884,
    website: "https://www.aslrobotics.com/",
  },
  {
    address: null,
    city: "Orlando",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1902",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Novelis/Rev Robotics/Metal Essence, Inc./Rockwell Automation/Gene Haas Foundation/Comcast NBC Universal/Walt Disney World Engineers/Intuitive Foundation/Orange County/Elise Cronin-Hurley&4-H",
    nickname: "Exploding Bacon",
    postal_code: "32812",
    rookie_year: 2006,
    school_name: "4-H",
    state_prov: "Florida",
    teamNumber: 1902,
    website: "http://www.explodingbacon.com",
  },
  {
    address: null,
    city: "Contoocook",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc1922",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Hopkinton Middle School & Hopkinton High School",
    nickname: "Oz-Ram",
    postal_code: "03229",
    rookie_year: 2006,
    school_name: "Hopkinton High School & Hopkinton Middle School",
    state_prov: "New Hampshire",
    teamNumber: 1922,
    website: "http://www.ozram1922.org",
  },
  {
    address: null,
    city: "Southington",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc195",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Mohawk Northeast/CyberKnights Robotics /Otis Elevator/Southington Public Schools/Lockheed Martin&CyberKnights Robotics",
    nickname: "CyberKnights",
    postal_code: "06489",
    rookie_year: 1998,
    school_name: "CyberKnights Robotics",
    state_prov: "Connecticut",
    teamNumber: 195,
    website: "http://www.team195.com",
  },
  {
    address: null,
    city: "Maple Valley",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2046",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "The Truck Shop/1-800-Got-Junk/West Coast Products&Tahoma Senior High School",
    nickname: "Bear Metal",
    postal_code: "98038",
    rookie_year: 2007,
    school_name: "Tahoma Senior High School",
    state_prov: "Washington",
    teamNumber: 2046,
    website: "http://tahomarobotics.org/",
  },
  {
    address: null,
    city: "New Brighton",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2052",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Groves Foundation/Medtronic/QONQR/Edlund Management&Irondale Senior High School",
    nickname: "KnightKrawler",
    postal_code: "55112",
    rookie_year: 2007,
    school_name: "Irondale Senior High School",
    state_prov: "Minnesota",
    teamNumber: 2052,
    website: "https://www.team2052.com",
  },
  {
    address: null,
    city: "Guilford",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2067",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Bishop's Orchards/Connecticut Manufacturing Innovation Fund/Medtronic&4-H&4H",
    nickname: "Apple Pi",
    postal_code: "06437",
    rookie_year: 2007,
    school_name: "4H & 4-H",
    state_prov: "Connecticut",
    teamNumber: 2067,
    website: "http://www.applepirobotics.org",
  },
  {
    address: null,
    city: "Fond du Lac",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2194",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "John Deere Horicon Works/Gene Haas Foundation/GE Healthcare/Belke Financial Group/Milwaukee School of Engineering/John & Sheila Boyle Foundation/Stone Foundation/Graham-Field&Fond Du Lac High School&Neighborhood Group",
    nickname: "Fondy Fire",
    postal_code: "54935",
    rookie_year: 2007,
    school_name: "Neighborhood Group & Fond Du Lac High School",
    state_prov: "Wisconsin",
    teamNumber: 2194,
    website: "http://fondyfire.com/",
  },
  {
    address: null,
    city: "Rockledge",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc233",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "NASA Kennedy Space Center/Brevard Public School/DoWSTEM/SpaceX/Boeing/RTX Raytheon/Bechtel/Argosy/Lockheed Martin/BAE/Intuitive Foundation&Cocoa Beach Jr Sr High School&Space Coast Jr Sr High School&Rockledge Senior High School",
    nickname: "The Pink Team",
    postal_code: "32955",
    rookie_year: 1999,
    school_name:
      "Cocoa Beach Jr Sr High School & Rockledge Senior High School & Space Coast Jr Sr High School",
    state_prov: "Florida",
    teamNumber: 233,
    website: "http://www.thepinkteam.net",
  },
  {
    address: null,
    city: "Rutland",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2370",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Alderman Chevrolet and Toyota/Killington Ski Resort/Killington Mountain Homes/Maine Drilling and Blasting&Stafford Technical Center&Family/Community",
    nickname: "IBOTS",
    postal_code: "05701",
    rookie_year: 2008,
    school_name: "Family/Community & Stafford Technical Center",
    state_prov: "Vermont",
    teamNumber: 2370,
    website: "https://ibots.rutlandarearobotics.org/",
  },
  {
    address: null,
    city: "Calumet",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2586",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Motorola Solutions/Great Lakes Sound and Vibration/James Dee/Carmen Sandretto/Calumet Electronics/Mohawk Technologies/Erico Electric/Koppers/Breakwater Federal Credit Union&Calumet High School",
    nickname: "Copper Bots",
    postal_code: "49913",
    rookie_year: 2008,
    school_name: "Calumet High School",
    state_prov: "Michigan",
    teamNumber: 2586,
    website: "http://www.copperbots.org",
  },
  {
    address: null,
    city: "Melrose",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2713",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Churchill Corp/King-White Family Foundation/Insource Services/Walmart/Brad Hutchinson Real Estate/Analog Devices/BAE Systems/Community Coalition of Melrose/Department of Defense/Gene Haas Foundation/Intuitive Foundation/Medtronic/Melrose Cooperative Bank Charitable Foundation/Melrose Cultural Council/Mitre/Motorola Solutions/PTC/Ramlose Foundation/RTX/Real Time Robotics/Salesforce/Schneider Electric/Tech Ed Products/Wolf Greenfield and Sacks&Melrose High School",
    nickname: "Red Hawk Robotics",
    postal_code: "02176",
    rookie_year: 2009,
    school_name: "Melrose High School",
    state_prov: "Massachusetts",
    teamNumber: 2713,
    website: "http:///www.iraiders.org",
  },
  {
    address: null,
    city: "La Grange",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2783",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "PMMI/Dow/Emerson/NI Emerson/Ablemarle/Modern Technology Solutions Inc/Cherry House/Global Granite/UPS/BAE P&S/Tony Malito/Budget Car Sales/Stock Yards Bank & Trust/Gene Haas Foundation&Family/Community",
    nickname: "Engineers of Tomorrow",
    postal_code: "40031",
    rookie_year: 2009,
    school_name: "Family/Community",
    state_prov: "Kentucky",
    teamNumber: 2783,
    website: "http://www.kyeot.com",
  },
  {
    address: null,
    city: "Mill Creek",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2910",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Boeing/Computer Concepts/Electroimpact/Gene Haas Foundation/Microsoft/Mill Creek Chamber of Commerce/Onshape/Reed Baldwin Redfellowship/SPEEA IFPTE Local 2001/Swerve Drive Specialties/Tacoma Screw/Washington Office of Superintendent of Public Instruction/BECU/Booked by Melissa Travel/EnerSys/Fabworks/T-Mobile Foundation/West Coast Products/Everett Public Schools/FIRST Washington/PLS/AmazingLife/Salon Ivory&Henry M. Jackson High School",
    nickname: "Jack in the Bot",
    postal_code: "98082",
    rookie_year: 2009,
    school_name: "Henry M. Jackson High School",
    state_prov: "Washington",
    teamNumber: 2910,
    website: "http://frcteam2910.org",
  },
  {
    address: null,
    city: "Colorado Springs",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc2996",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Jaxson Engineering and Maintance/DoD STEM/GENE HAAS FOUNDATION/Vertec Tool, Inc/L3Harris/Azhanti Systems/JPM Engineering/N.A.W.I.C./Trail's End Homebuilders/Westside Boot and Shoe&Coronado High School",
    nickname: "Cougars Gone Wired",
    postal_code: "80904",
    rookie_year: 2009,
    school_name: "Coronado High School",
    state_prov: "Colorado",
    teamNumber: 2996,
    website: "http://www.team2996.com",
  },
  {
    address: null,
    city: "Dallas",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3005",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Texas Instruments/REV Robotics/Vickery Meadows Foundation/General Motors&Emmett J Conrad High School",
    nickname: "RoboChargers",
    postal_code: "75231",
    rookie_year: 2009,
    school_name: "Emmett J Conrad High School",
    state_prov: "Texas",
    teamNumber: 3005,
    website: "http://www.frc3005.com",
  },
  {
    address: null,
    city: "Ballston Spa",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3044",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Ballston Spa National Bank/GE Aerospace/GLOBALFOUNDRIES/Town of Malta Community Foundation/Gene Haas Foundation/Stewart's Shops Holiday Match/John Yagieski/JLK Global Fund - Holiday Inn/P1 Industries/Knauf Insulation/Phillips/IBM/Coffee Planet&Ballston Spa High School",
    nickname: "Team 0xBE4",
    postal_code: "12020",
    rookie_year: 2009,
    school_name: "Ballston Spa High School",
    state_prov: "New York",
    teamNumber: 3044,
    website: "https://frcteam3044.team/",
  },
  {
    address: null,
    city: "San Jose",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3256",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Apple/Intuitive Foundation/Biola University/FIRST NorCal/Pop Up Tea&Valley Christian High School",
    nickname: "WarriorBorgs",
    postal_code: "95111",
    rookie_year: 2010,
    school_name: "Valley Christian High School",
    state_prov: "California",
    teamNumber: 3256,
    website: "http://www.vcrobotics.net/",
  },
  {
    address: null,
    city: "New London - Spicer",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3276",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Medtronic/Dahmes Stainless/Relco/Chappell Central/Jason Dowdey Weichert Reality&New London-Spicer High School",
    nickname: "TOOLCATS",
    postal_code: "56273",
    rookie_year: 2010,
    school_name: "New London-Spicer High School",
    state_prov: "Minnesota",
    teamNumber: 3276,
    website: "https://www.nls.k12.mn.us/Page/2153#calendar4399/20200301/month",
  },
  {
    address: null,
    city: "Queretaro",
    country: "Mexico",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3354",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Viva/Wago/Autocom/Herco/Rastreo 365/Wundertec/Gogo Shopping/NobleProg&PrepaTec Queretaro",
    nickname: "PrepaTec - TecDroid",
    postal_code: "76130",
    rookie_year: 2010,
    school_name: "PrepaTec Queretaro",
    state_prov: "Querétaro",
    teamNumber: 3354,
    website: "http://www.tecdroid3354.com",
  },
  {
    address: null,
    city: "Ambler",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc341",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Johnson & Johnson/Boeing/Comcast NBCUniversal/DoD STEM/Picatinny STEM/Gene Haas Foundation/ASTM International/CAES/TE Connectivity/Lockheed Martin/BAE Systems/West Coast Products/Sofidel/Pennoni/Penn State Great Valley/Computer Components Corporation/Minuteman Press Ambler&Wissahickon High School",
    nickname: "Miss Daisy",
    postal_code: "19002",
    rookie_year: 2000,
    school_name: "Wissahickon High School",
    state_prov: "Pennsylvania",
    teamNumber: 341,
    website: "http://www.team341.com/",
  },
  {
    address: null,
    city: "Richmond",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc346",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Scott & Michelle Haymans/Dominion Energy/Blueprint Automation/Ryson International/Dupont/The Boffemmyer Family/D&D Mechanical/Chesterfield Power Station/SW Funk Industries/BFPE International/Jewett Automation/HTT ISOMEMBRANE Team/James River Stucco/Owens Family/Richard Lutge/Governor's Academy for Engineering Students at L.C. Bird High School/L.C. Bird High School&Lloyd C Bird High School",
    nickname: "RoboHawks",
    postal_code: "23832",
    rookie_year: 2000,
    school_name: "Lloyd C Bird High School",
    state_prov: "Virginia",
    teamNumber: 346,
    website: "http://www.robohawks346.com/",
  },
  {
    address: null,
    city: "Melbourne",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc386",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Brevard Public Schools/NASA Kennedy Space Center/The Step It Up Foundation/L3Harris Technologies, Inc./Bechtel Corporation/Gene Haas Foundation/Leonardo DRS, Inc./RTX Corporation&Melbourne High School",
    nickname: "Team Voltage",
    postal_code: "32901",
    rookie_year: 2000,
    school_name: "Melbourne High School",
    state_prov: "Florida",
    teamNumber: 386,
    website: "http://www.teamvoltage.org",
  },
  {
    address: null,
    city: "Knoxville",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc3966",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Bechtel/TVA/UCOR/Knox County Schools /L&N STEM Academy PTSA&L&N STEM Academy",
    nickname: "Gryphon Command",
    postal_code: "37902",
    rookie_year: 2012,
    school_name: "L&N STEM Academy",
    state_prov: "Tennessee",
    teamNumber: 3966,
    website: "http://lnstempunks.org/",
  },
  {
    address: null,
    city: "Poolesville",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4099",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "NASA/Maryland Space Business Roundtable/Bloomberg/Leidos/MCR-SGA & Family/Community",
    nickname: "The Falcons",
    postal_code: "20837",
    rookie_year: 2012,
    school_name: "Family/Community",
    state_prov: "Maryland",
    teamNumber: 4099,
    website: "https://www.team4099.com/",
  },
  {
    address: null,
    city: "Fort Worth",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4206",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Regan Scientific Instruments/Stampede Sports Arena/B&F Finance/Bell/Frank W. Neal & Associates/Uptown Pup - Nature & Nurture/ECI Management/Nolan Catholic High School&Nolan Catholic High School",
    nickname: "Robo Vikes",
    postal_code: "76103",
    rookie_year: 2012,
    school_name: "Nolan Catholic High School",
    state_prov: "Texas",
    teamNumber: 4206,
    website: "http://www.team4206.net",
  },
  {
    address: null,
    city: "Buffalo",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc424",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Alkegen/MOOG/Matt Enstice/Pooely INC./VIRDI/Grams/NASA&Bausch & Lomb Incorporated&Churchville-Chili High School",
    nickname: "Rust Belt Robotics",
    postal_code: "14428",
    rookie_year: 2000,
    school_name: "Churchville-Chili High School & Bausch & Lomb Incorporated",
    state_prov: "New York",
    teamNumber: 424,
    website: "http://www.team340.org",
  },
  {
    address: null,
    city: "Taipei",
    country: "Chinese Taipei",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4253",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Taipei American School",
    nickname: "Raid Zero",
    postal_code: "11152",
    rookie_year: 2012,
    school_name: "Taipei American School",
    state_prov: "Taipei Special Municipality",
    teamNumber: 4253,
    website: "http://www.firstinspires.org/",
  },
  {
    address: null,
    city: "TORREON",
    country: "Mexico",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4400",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "PEÑOLES/Grupo SIMSA/JOHN DEERE/REV Robotics&COLEGIO CERVANTES DE TORREON",
    nickname: "Cerbotics - Peñoles",
    postal_code: "27276",
    rookie_year: 2012,
    school_name: "COLEGIO CERVANTES DE TORREON",
    state_prov: "Coahuila",
    teamNumber: 4400,
    website: "http://www.cerbotics.com",
  },
  {
    address: null,
    city: "Research Triangle Park",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4561",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Alfredo Systems/John Deere/Google&Research Triangle High School",
    nickname: "TerrorBytes",
    postal_code: "27709",
    rookie_year: 2013,
    school_name: "Research Triangle High School",
    state_prov: "North Carolina",
    teamNumber: 4561,
    website: "http://terrorbytes.org/",
  },
  {
    address: null,
    city: "Hakfar Hayarok",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc4590",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Hakfar Hayarok School&Hakfar Hayarok",
    nickname: "GreenBlitz",
    postal_code: "4780000",
    rookie_year: 2013,
    school_name: "Hakfar Hayarok",
    state_prov: "Tel-Aviv",
    teamNumber: 4590,
    website: "http://www.firstinspires.org/",
  },
  {
    address: null,
    city: "Essexville",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5216",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Bay Composite/Dow Chemical/FIRST of the Great Lake Bay Region/SC Johnson/Nexteer Automotive/MDE/Larsen Graphics/Consumers Energy/Toyota/AT & T/Aptar Group & Garber High School",
    nickname: "E-Ville Empire",
    postal_code: "48732",
    rookie_year: 2014,
    school_name: "Garber High School",
    state_prov: "Michigan",
    teamNumber: 5216,
    website: "http://www.e-hps.net",
  },
  {
    address: null,
    city: "Pearland",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5414",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "NASA/DOW/Texas Workforce Commission/Ascend Cares Foundation/Gene Haas Foundation/BNY Mellon/Intuitive Foundation/STEM Savvy Brew/Pearland Lions Club/Boeing/Conoco Phillips/Chevron/Pearland Police Officers Association/Endress & Hauser/AYLUS&Pearland High School&Glenda Dawson High School&Robert Turner Colege-Career HS",
    nickname: "Pearadox",
    postal_code: "77584",
    rookie_year: 2015,
    school_name:
      "Pearland High School & Robert Turner Colege-Career HS & Glenda Dawson High School",
    state_prov: "Texas",
    teamNumber: 5414,
    website: "https://www.pearadox5414.org",
  },
  {
    address: null,
    city: "Falls Church",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5549",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Kform/Raytheon Technologies/Lockheed Martin/Booz Allen Hamilton/Leidos/Solidworks/Nvidia/SideTrak/Ragnar&Marshall High School",
    nickname: "Gryphon Robotics",
    postal_code: "22043",
    rookie_year: 2015,
    school_name: "Marshall High School",
    state_prov: "Virginia",
    teamNumber: 5549,
    website: "https://www.frc5549.org/",
  },
  {
    address: null,
    city: "Kings Park",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5736",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Zebra Technologies/America's NAVY/Kings Park School District & Booster Organization&Kings Park High School",
    nickname: "Kingsmen Robotics",
    postal_code: "11754",
    rookie_year: 2015,
    school_name: "Kings Park High School",
    state_prov: "New York",
    teamNumber: 5736,
    website: "https://t.co/wI5UM40qti",
  },
  {
    address: null,
    city: "Cuernavaca",
    country: "Mexico",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5948",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Prepa Tec Cuernavaca/Bridgestone/Würth/Baxter&Instituto Tecnológico y de estudios superiores de Monterrey",
    nickname: "PrepaTec - Lebotics",
    postal_code: "62790",
    rookie_year: 2016,
    school_name: "Instituto Tecnológico y de estudios superiores de Monterrey",
    state_prov: "Morelos",
    teamNumber: 5948,
    website: "Coming Soon",
  },
  {
    address: null,
    city: "Tel Aviv",
    country: "Israel",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc5951",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Josh and Judy Weston/Tel-Aviv municipality/Tel Aviv foundation&the Natan Alterman school - Tichonet",
    nickname: "Makers Assemble",
    postal_code: "6937802",
    rookie_year: 2016,
    school_name: "the Natan Alterman school - Tichonet",
    state_prov: "Tel-Aviv",
    teamNumber: 5951,
    website: "http://www.firstinspires.org/",
  },
  {
    address: null,
    city: "Granada Hills",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc599",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Walt Disney Animation Studios/Gene Haas Foundation/Granada Hills South Neighborhood Council/Chris Siegert&Granada Hills Charter High Sch",
    nickname: "The Robodox",
    postal_code: "91344",
    rookie_year: 2001,
    school_name: "Granada Hills Charter High Sch",
    state_prov: "California",
    teamNumber: 599,
    website: "http://www.therobodox.org",
  },
  {
    address: null,
    city: "Palo Alto",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6036",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Gene Haas/TE Connectivity&Palo Alto Youth Robotics Association",
    nickname: "Peninsula Robotics",
    postal_code: "94301",
    rookie_year: 2016,
    school_name: "Palo Alto Youth Robotics Association",
    state_prov: "California",
    teamNumber: 6036,
    website: "https://team6036.github.io/",
  },
  {
    address: null,
    city: "San Jose",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc604",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Leland High School FRC Team 604 Quixilver/Apple/Google/Gene Haas Foundation/ARM/BAE Systems/Intuitive Surgical Foundation/Nvidia/West Coast Products/PGE/Almaden Valley Women's Club/604 Alumni and Parents/In-Kind: 100 Black Men-Hurricane Electric Internet Services-SolidWorks-OnShape-GitHub-FabWorks&Leland High School",
    nickname: "Quixilver",
    postal_code: "95120",
    rookie_year: 2001,
    school_name: "Leland High School",
    state_prov: "California",
    teamNumber: 604,
    website: "http://604Robotics.com",
  },
  {
    address: null,
    city: "Surprise",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6352",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "City of Surprise/Tundras to Sedona/DISCOUNT TIRE/Kiwanis Club of North Phoenix/General Dynamics/Gene Haas Foundation/Verizon/Aero Financial/Hunter Contracting Company/Cerity Partners/Koehring Heavy Duty/Ridgeline/Waymo/Czoka Racing Engines&Family/Community",
    nickname: "LAUNCH TEAM",
    postal_code: "85382",
    rookie_year: 2017,
    school_name: "Family/Community",
    state_prov: "Arizona",
    teamNumber: 6352,
    website: "http://bit.ly/6352Web",
  },
  {
    address: null,
    city: "istanbul",
    country: "Türkiye",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6436",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "WATTOS/MUTLUSAN ELECTRIC/BORSA İSTANBUL/BAŞAKŞEHİR BELEDİYESİ/FİKRET YÜKSEL FOUNDATION/AZİM REKLAM VE ELEKTRONİK SANAYİ/EFELER LAZER/DÜRÜMLE&Borsa Istanbul Başakşehir Mesleki ve Teknik Anadolu Lisesi",
    nickname: "NARBULUT PARS ROBOTICS",
    postal_code: "34480",
    rookie_year: 2017,
    school_name: "Borsa Istanbul Başakşehir Mesleki ve Teknik Anadolu Lisesi",
    state_prov: "Istanbul",
    teamNumber: 6436,
    website: "http://www.parsrobotics.org/",
  },
  {
    address: null,
    city: "MONTERREY",
    country: "Mexico",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6647",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "PrepaTec/John Deere/Gene Haas Foundation/Qualcomm/Benevity/Sap Labs Latin America/McGraw Hill/Equitek&PrepaTec Eugenio Garza Lagüera",
    nickname: "PrepaTec - VOLTEC",
    postal_code: "64890",
    rookie_year: 2017,
    school_name: "PrepaTec Eugenio Garza Lagüera",
    state_prov: "Nuevo León",
    teamNumber: 6647,
    website: "http://voltec6647.com",
  },
  {
    address: null,
    city: "Carson",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc687",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Gene Haas Foundation/Norris Foundation/Honda/Boeing/Raytheon/NASA/PG&E Corporate Foundation/DreamMakers Fund/CAMS PTSO/Raising Cane's/OurOwnStyle&California Academy Math & Sci",
    nickname: "The Nerd Herd",
    postal_code: "90747",
    rookie_year: 2001,
    school_name: "California Academy Math & Sci",
    state_prov: "California",
    teamNumber: 687,
    website: "http://www.camsrobotics.org",
  },
  {
    address: null,
    city: "Beachwood",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc695",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Board of Education & Beachwood High School",
    nickname: "Bison Robotics",
    postal_code: "44122",
    rookie_year: 2001,
    school_name: "Beachwood High School",
    state_prov: "Ohio",
    teamNumber: 695,
    website: "http://www.team695.com",
  },
  {
    address: null,
    city: "Göztepe",
    country: "Türkiye",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc6988",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Norm Holding/Ege Pen/Fikret Yüksel Organization/Solidworks Corp./E.C.A./acigarage&American Collegiate Institute",
    nickname: "ACI35",
    postal_code: "35290",
    rookie_year: 2018,
    school_name: "American Collegiate Institute",
    state_prov: "Izmir",
    teamNumber: 6988,
    website: "https://www.team6988.com",
  },
  {
    address: null,
    city: "Ludington",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc7160",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Precision Design Inc./Mason County Foundation - Lee & Joan Schoenherr/UACJ - Whitehall Industries/MiSTEM Region 9 West Shore ESD/Occidental Chemical/Cone Drive/Great Lakes Energy Foundation/Carter Lumber/Fastenal&Ludington High School",
    nickname: "Ludington O-Bots",
    postal_code: "49431",
    rookie_year: 2018,
    school_name: "Ludington High School",
    state_prov: "Michigan",
    teamNumber: 7160,
    website: "http://ludingtonrobotics.org",
  },
  {
    address: null,
    city: "Meredith",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc8046",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "NH Department Of Education/Meredith Village Savings Bank/3M/Meredith Rotary/REV Robotics/Boeing/BAE Systems&Inter-Lakes Jr Sr High School",
    nickname: "LakerBots",
    postal_code: "03253",
    rookie_year: 2020,
    school_name: "Inter-Lakes Jr Sr High School",
    state_prov: "New Hampshire",
    teamNumber: 8046,
    website: null,
  },
  {
    address: null,
    city: "Warren",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc818",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "General Motors/McNaughton-McKay/Warren Consolidated Schools & Sterling Heights High School",
    nickname: "The Steel Armadillos",
    postal_code: "48093",
    rookie_year: 2002,
    school_name: "Sterling Heights High School",
    state_prov: "Michigan",
    teamNumber: 818,
    website: "https://www.team818.com/",
  },
  {
    address: null,
    city: "Blissfield",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc8373",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Dana Incorporated/Hi-Lex/Lenco Painting Inc./Blissfield Veterinary Clinic/H & H Repair Inc.&Blissfield High School",
    nickname: "The Flying Octopi",
    postal_code: "49228",
    rookie_year: 2020,
    school_name: "Blissfield High School",
    state_prov: "Michigan",
    teamNumber: 8373,
    website: null,
  },
  {
    address: null,
    city: "Carmel",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc868",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Martin Marietta/Resultant/APTIV Foundation/Thrifty Bot/Lockheed Martin/Texas Instruments/Joe's Grille/Gaylor Electric/Heldman Exteriors/Kiwanis Club of Carmel/Precision Additive/Seven Corners/SRS Distribution/Rider Kenley&Carmel Senior High School",
    nickname: "TechHOUNDS",
    postal_code: "46032",
    rookie_year: 2002,
    school_name: "Carmel Senior High School",
    state_prov: "Indiana",
    teamNumber: 868,
    website: "http://www.techhounds.com",
  },
  {
    address: null,
    city: "Bridgewater",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc88",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Point 32 Health Foundation/Bridgewater-Raynham Regional School District/The Wall Family/ACME Engineering/RTX/Intex/EM Duggan/Gene Haas Foundation/Formlabs/Tierpoint/Qualcomm/Johnson & Johnson MedTech&Bridgewater-Raynham Reg HS",
    nickname: "TJ²",
    postal_code: "02324",
    rookie_year: 1996,
    school_name: "Bridgewater-Raynham Reg HS",
    state_prov: "Massachusetts",
    teamNumber: 88,
    website: "http://www.tj2.org",
  },
  {
    address: null,
    city: "Çankaya",
    country: "Türkiye",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9029",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "ODTÜ Geliştirme Vakfı&Family/Community",
    nickname: "Team NF",
    postal_code: null,
    rookie_year: 2023,
    school_name: "Family/Community",
    state_prov: "Ankara",
    teamNumber: 9029,
    website: null,
  },
  {
    address: null,
    city: "Searcy",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9067",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Gene Haas Foundation/Charlie's Auto Paint & Body/Ridout Lumber/OnlineMetals.com&Searcy High School",
    nickname: "The Goonies",
    postal_code: null,
    rookie_year: 2023,
    school_name: "Searcy High School",
    state_prov: "Arkansas",
    teamNumber: 9067,
    website: null,
  },
  {
    address: null,
    city: "Plano",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9128",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "JAMY Properties/LXT/Gently/Texas Instruments/Sandia National Labs/T-Mobile Foundation/Gene Haas Foundation/Apple/Google/Texas Workforce Commission/MedRock/Deepen AI/Discreetize&Family/Community",
    nickname: "ITKAN Robotics",
    postal_code: null,
    rookie_year: 2023,
    school_name: "Family/Community",
    state_prov: "Texas",
    teamNumber: 9128,
    website: null,
  },
  {
    address: null,
    city: "Pigeon",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9245",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "AgriValley Communications/Autokiniton/Bergman Builders/Buchholz Transport/Har Jo's Ben Franklin/Huron Casting/McCain Plumbing and Heating/TAAZ Seed Sales/Thumb Bank and Trust&Laker High School",
    nickname: "Laker Dreadnoughts",
    postal_code: null,
    rookie_year: 2023,
    school_name: "Laker High School",
    state_prov: "Michigan",
    teamNumber: 9245,
    website: null,
  },
  {
    address: null,
    city: "Mukwonago",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc930",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Komatsu/TAPCO/NEXT Electric/West Coast Products/The Thrifty Bot&Mukwonago High School",
    nickname: "Mukwonago BEARs",
    postal_code: "53149",
    rookie_year: 2002,
    school_name: "Mukwonago High School",
    state_prov: "Wisconsin",
    teamNumber: 930,
    website: "http://team930.com/",
  },
  {
    address: null,
    city: "Downey",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9408",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Mary R. Stauffer Foundation/Downey Unified School District/Boeing/NASA/RTX - Raytheon Technology&Warren High School",
    nickname: "Warren Warbots",
    postal_code: null,
    rookie_year: 2024,
    school_name: "Warren High School",
    state_prov: "California",
    teamNumber: 9408,
    website: null,
  },
  {
    address: null,
    city: "Woodinville",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc9450",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Northshore School District/OSPI/Dunn Lumber/Out of the Box Manufacturing /FIRST/Boeing/SPEEA /NASA/Gene Haas Foundation&Woodinville High School",
    nickname: "Velocity Raptors",
    postal_code: null,
    rookie_year: 2024,
    school_name: "Woodinville High School",
    state_prov: "Washington",
    teamNumber: 9450,
    website: null,
  },
  {
    address: null,
    city: "Bellevue",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc948",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "XTool/Polymaker/Microsoft/Google/Bellevue Schools Foundation/Hatchx/Somerset PTSA/First Washington/Amazon&Newport High School",
    nickname: "NRG (Newport Robotics Group)",
    postal_code: "98006",
    rookie_year: 2002,
    school_name: "Newport High School",
    state_prov: "Washington",
    teamNumber: 948,
    website: "http://www.nrg948.com",
  },
  {
    address: null,
    city: "Atascadero",
    country: "USA",
    gmaps_place_id: null,
    gmaps_url: null,
    key: "frc973",
    lat: null,
    lng: null,
    location_name: null,
    motto: null,
    name: "Family/Community",
    nickname: "Greybots",
    postal_code: "93422",
    rookie_year: 2002,
    school_name: "Family/Community",
    state_prov: "California",
    teamNumber: 973,
    website: "http://www.greybots.com",
  },
];

export const FRC_TEAM_NUMBERS = FRC_TEAMS.map((team) => team.teamNumber);

export type TeamString<N extends number = number> = `frc${N}`;
export const teamStringToTeamNumber = <
  N extends number,
  S extends string = TeamString<N>,
>(
  teamString: S,
): N => Number(teamString.replace("frc", "")) as N;
